apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "storage-migration.fullname" . }}
  labels:
    {{- include "storage-migration.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "storage-migration.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if eq .Values.migrationType "single" }}
            {{- if .Values.storage.minio.secretName }}
            - name: DATASTORE_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.storage.minio.secretName }}"
                  key: "{{ .Values.storage.minio.accesskeyName }}"
            - name: DATASTORE_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.storage.minio.secretName }}"
                  key: "{{ .Values.storage.minio.secretkeyName }}"
            {{- else }}
            - name: DATASTORE_ACCESSKEY
              value: "{{ .Values.storage.minio.accesskey }}"
            - name: DATASTORE_SECRETKEY
              value: "{{ .Values.storage.minio.secretkey }}"
            {{- end }}
            - name: DATASTORE_ENDPOINT
              value: "{{ .Values.storage.minio.endpoint }}"
            - name: DATASTORE_BUCKETPREFIX
              value: "{{ .Values.storage.bucket.bucketPrefix | default "prj-" }}"
            - name: DATASTORE_DEFAULTBUCKETNAME
              value: "{{ .Values.storage.bucket.bucketForPlugins }}" 
            - name: DATASTORE_SINGLEBUCKETNAME
              value: "{{ .Values.storage.bucket.bucketMinioSingleName }}"
            - name: DATASTORE_REGION
              value: "{{ .Values.storage.s3.region }}"
            - name: DATASTORE_REMOVE_AFTER_MIGRATION
              value: "{{ .Values.storage.removeAfterMigration }}"
            - name: RP_DB_HOST
              value: "{{ .Values.postgresql.endpoint.address }}"
            - name: RP_DB_USER
              value: "{{ .Values.postgresql.endpoint.user }}"
            - name: RP_DB_PASS
            {{ if .Values.postgresql.SecretName }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.SecretName }}"
                  key: "postgresql-password"
            {{ else }}
              value: "{{ .Values.postgresql.endpoint.password }}"
            {{ end }}
            - name: RP_DB_NAME
              value: "{{ .Values.postgresql.endpoint.dbName }}"
            - name: DATASTORE_TYPE
              value: "minio"
          {{- else if eq .Values.migrationType "s3" }}
            - name: MINIO_ENDPOINT
              value: "{{ .Values.storage.minio.endpoint }}"
            - name: MINIO_ACCESS_KEY
              value: "{{ .Values.storage.minio.accesskey }}"
            - name: MINIO_SECRET_KEY
              value: "{{ .Values.storage.minio.secretkey }}"
            - name: S3_ENDPOINT
              value: "{{ .Values.storage.s3.endpoint }}"
            - name: S3_ACCESS_KEY
              value: "{{ .Values.storage.s3.accesskey }}"
            - name: S3_SECRET_KEY
              value: "{{ .Values.storage.s3.secretkey }}"
            - name: MINIO_SINGLE_BUCKET
              value: "{{ .Values.storage.bucket.bucketMinioSingleName }}" 
            - name: S3_SINGLE_BUCKET
              value: "{{ .Values.storage.bucket.bucketS3SingleName }}"  
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
